require:
  - ./lib/rubocop_autocorrect.rb
  - rubocop-rails
inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'config/*/*'
    - 'config/{application,boot,importmap,puma}.rb'
    - 'config/boot.rb'
    - 'script/**/*'
    - 'bin/{rails,rake,bundle,importmap,setup}'
    - 'test/application_system_test_case.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'config.ru'
    - 'rakefile'
Layout/EndOfLine:
  EnforcedStyle: lf

Rails/I18nLocaleTexts:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'app/helpers/**/*'
    - 'test/**/*'
    - 'app/models/application_record.rb'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Metrics/ClassLength:
  Max: 150
