inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'config/*/*'
    - 'config/{application,boot,importmap,puma}.rb'
    - 'config/boot.rb'
    - 'script/**/*'
    - 'bin/{rails,rake,bundle,importmap,setup}'
    - 'test/application_system_test_case.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'config.ru'
    - 'rakefile'
Style/EndOfLine:
  EnforcedStyle: lf